format = """
[â”Œî‚¶](#48349a)\
$username\
[î‚°](bg:#DA627D fg:#48349a)\
$directory\
[î‚°](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[î‚°](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$terraform\
[î‚°](fg:#86BBD8 bg:#06969A)\
$docker_context\
[î‚°](fg:#06969A bg:#33658A)\
$time\
[î‚° ](fg:#33658A)
[â””â”€ï” ](fg:#48349a)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#48349a"
style_root = "bg:#8e1414"
format = '[$user ]($style)'

[directory]
style = "fg:#373737 bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 8
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "fg:#505050 bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#505050 bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ â™¥ $time ]($style)'

[terraform]
symbol = "ğŸğŸ’¨"
style = "fg:#373737 bg:#86BBD8"
format = '[ $symbol ($version) $workspace ]($style)'
